# Config file for - http://www.appveyor.com/
# Validate here - https://ci.appveyor.com/tools/validate-yaml

version: 1.0.{build}-{branch}

init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: "12"

platform: x64

matrix:
  fast_finish: true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version x86
  - yarn install --non-interactive

test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn run example:dev
  - yarn run example:prod

cache:
  - node_modules -> package.json,yarn,lock

branches:
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

# Don't actually build.
build: off
